# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Form_startup.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_startup(object):
    def setupUi(self, Form_startup):
        Form_startup.setObjectName("Form_startup")
        Form_startup.setWindowModality(QtCore.Qt.NonModal)
        Form_startup.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_startup.sizePolicy().hasHeightForWidth())
        Form_startup.setSizePolicy(sizePolicy)
        Form_startup.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form_startup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 761, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_restore = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_restore.setObjectName("pushButton_restore")
        self.horizontalLayout.addWidget(self.pushButton_restore)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_test_list = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_test_list.sizePolicy().hasHeightForWidth())
        self.tableWidget_test_list.setSizePolicy(sizePolicy)
        self.tableWidget_test_list.setObjectName("tableWidget_test_list")
        self.tableWidget_test_list.setColumnCount(8)
        self.tableWidget_test_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_list.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.tableWidget_test_list)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_see_last_error = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_see_last_error.setObjectName("pushButton_see_last_error")
        self.horizontalLayout_4.addWidget(self.pushButton_see_last_error)
        self.pushButton_preferences = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_preferences.setObjectName("pushButton_preferences")
        self.horizontalLayout_4.addWidget(self.pushButton_preferences)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_run = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_4.addWidget(self.pushButton_run)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form_startup)
        QtCore.QMetaObject.connectSlotsByName(Form_startup)

    def retranslateUi(self, Form_startup):
        _translate = QtCore.QCoreApplication.translate
        Form_startup.setWindowTitle(_translate("Form_startup", "PyQt tests"))
        self.label.setText(_translate("Form_startup", "Command prompt program test."))
        self.label_2.setText(_translate("Form_startup", "Test manager"))
        self.pushButton_add.setText(_translate("Form_startup", "add"))
        self.pushButton_restore.setText(_translate("Form_startup", "restore"))
        item = self.tableWidget_test_list.horizontalHeaderItem(0)
        item.setText(_translate("Form_startup", "info"))
        item = self.tableWidget_test_list.horizontalHeaderItem(1)
        item.setText(_translate("Form_startup", "type"))
        item = self.tableWidget_test_list.horizontalHeaderItem(2)
        item.setText(_translate("Form_startup", "title"))
        item = self.tableWidget_test_list.horizontalHeaderItem(3)
        item.setText(_translate("Form_startup", "test?"))
        item = self.tableWidget_test_list.horizontalHeaderItem(4)
        item.setText(_translate("Form_startup", "last result"))
        item = self.tableWidget_test_list.horizontalHeaderItem(5)
        item.setText(_translate("Form_startup", "data"))
        item = self.tableWidget_test_list.horizontalHeaderItem(6)
        item.setText(_translate("Form_startup", "edit"))
        item = self.tableWidget_test_list.horizontalHeaderItem(7)
        item.setText(_translate("Form_startup", "delete"))
        self.pushButton_see_last_error.setText(_translate("Form_startup", "see last error"))
        self.pushButton_preferences.setText(_translate("Form_startup", "preferences"))
        self.pushButton_run.setText(_translate("Form_startup", "run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_startup = QtWidgets.QWidget()
    ui = Ui_Form_startup()
    ui.setupUi(Form_startup)
    Form_startup.show()
    sys.exit(app.exec_())

